AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/*.rb'
  Exclude:
    - doc/**/*
    - docs/**/*
    - examples/**/*
    - rcov/**/*
    - spec/**/*
    - Changelog
    - Guardfile
    - Gemfile
    - LICENSE
    - Rakefile
    - README.rdoc
    - '**/*.bat'
    - '**/*.gem'
    - '**/*.md'
    - '**/*.yml'
    - '.gitignore/**/*'
    - '.yardoc/**/*'
    - '.yardopts/**/*'
    - lib/work*.rb
    - ~/*

Style/AsciiComments:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DateTime:
  Enabled: false
